services:
  pinggy:
    profiles: ["temporary-preview"]
    build:
      context: .
      dockerfile: Dockerfile.tunnel
    restart: unless-stopped
    depends_on:
      web:
        condition: service_started
