#!/usr/bin/env python3
"""Produce a validated synthetic Sawyer trajectory package for Gate 1.

The package is generated by a real MuJoCo/MetaWorld execution backend and is
written in two trainable interchange forms:

* LeRobotDataset v3 Parquet/MP4, validated with the official LeRobot loader.
* RLDS-compatible TFRecord episodes, validated record-by-record.

This is a narrow technical production baseline.  It is not buyer-owned
evidence, a real-robot run, or permission to mark procurement Gate 1 passed.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import math
import shutil
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

import gymnasium as gym
import numpy as np
import torch
from PIL import Image
from lerobot.datasets import LeRobotDataset, LeRobotDatasetMetadata
from metaworld.policies import ENV_POLICY_MAP
from tfrecord.reader import tfrecord_loader
from tfrecord.writer import TFRecordWriter
from torch.utils.data import DataLoader


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = ROOT.parent / "results" / "qtail_gate1_metaworld_synthetic"
REPO_ID = "qtail/metaworld-sawyer-gate1-v3"
TASKS = ("reach-v3", "button-press-v3", "pick-place-v3")
DEFAULT_ALLOCATION = {
    "reach-v3": 50,
    "button-press-v3": 7,
    "pick-place-v3": 7,
}
ROBOT_TYPE = "sawyer_metaworld_mujoco"


@dataclass
class Episode:
    task: str
    task_index: int
    episode_seed: int
    observations: list[np.ndarray]
    images: list[np.ndarray]
    actions: list[np.ndarray]
    rewards: list[float]
    success: bool
    episode_return: float


def now() -> str:
    return datetime.now(UTC).isoformat()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def parse_allocation(value: str) -> dict[str, int]:
    parts = [int(item) for item in value.split(",")]
    if len(parts) != len(TASKS) or any(item < 1 for item in parts):
        raise argparse.ArgumentTypeError(f"Expected {len(TASKS)} positive comma-separated counts")
    return dict(zip(TASKS, parts, strict=True))


def feature_contract(image_size: int) -> dict:
    return {
        "observation.state": {
            "dtype": "float32",
            "shape": (39,),
            "names": [f"state_{index}" for index in range(39)],
        },
        "observation.images.rgb": {
            "dtype": "video",
            "shape": (image_size, image_size, 3),
            "names": ["height", "width", "channels"],
        },
        "action": {
            "dtype": "float32",
            "shape": (4,),
            "names": ["delta_x", "delta_y", "delta_z", "gripper"],
        },
        "reward": {"dtype": "float32", "shape": (1,), "names": ["reward"]},
        "discount": {"dtype": "float32", "shape": (1,), "names": ["discount"]},
        "done": {"dtype": "bool", "shape": (1,), "names": ["done"]},
        "success": {"dtype": "bool", "shape": (1,), "names": ["success"]},
    }


def create_env(task: str, seed: int):
    return gym.make(
        "Meta-World/MT1",
        env_name=task,
        seed=seed,
        render_mode="rgb_array",
        disable_env_checker=True,
    )


def resize_frame(frame: np.ndarray, image_size: int) -> np.ndarray:
    image = Image.fromarray(np.asarray(frame, dtype=np.uint8), mode="RGB")
    if image.size != (image_size, image_size):
        image = image.resize((image_size, image_size), Image.Resampling.LANCZOS)
    return np.asarray(image, dtype=np.uint8)


def collect_episode(
    env,
    expert,
    *,
    task: str,
    task_index: int,
    episode_seed: int,
    max_steps: int,
    action_noise: float,
    image_size: int,
) -> Episode:
    rng = np.random.default_rng(episode_seed)
    observation, _ = env.reset(seed=episode_seed)
    observations: list[np.ndarray] = []
    images: list[np.ndarray] = []
    actions: list[np.ndarray] = []
    rewards: list[float] = []
    success = False
    episode_return = 0.0
    for _step in range(max_steps):
        expert_action = np.asarray(expert.get_action(observation), dtype=np.float32)
        action = np.clip(
            expert_action + rng.normal(0.0, action_noise, size=4),
            -1.0,
            1.0,
        ).astype(np.float32)
        observations.append(np.asarray(observation, dtype=np.float32))
        images.append(resize_frame(env.render(), image_size))
        actions.append(action)
        observation, reward, terminated, truncated, info = env.step(action)
        reward_value = float(reward)
        rewards.append(reward_value)
        episode_return += reward_value
        success = success or bool(info.get("success"))
        if success or terminated or truncated:
            break
    return Episode(
        task=task,
        task_index=task_index,
        episode_seed=episode_seed,
        observations=observations,
        images=images,
        actions=actions,
        rewards=rewards,
        success=success,
        episode_return=episode_return,
    )


def image_jpeg_bytes(image: np.ndarray) -> bytes:
    buffer = io.BytesIO()
    Image.fromarray(image, mode="RGB").save(buffer, format="JPEG", quality=92, optimize=True)
    return buffer.getvalue()


def write_rlds_episode(writer: TFRecordWriter, episode: Episode, fps: int) -> None:
    steps = len(episode.actions)
    is_first = [1] + [0] * (steps - 1)
    is_last = [0] * (steps - 1) + [1]
    instruction = episode.task.encode("utf-8")
    writer.write({
        "episode_metadata/task": (instruction, "byte"),
        "episode_metadata/robot_type": (ROBOT_TYPE.encode("utf-8"), "byte"),
        "episode_metadata/production_backend": (b"MuJoCo/MetaWorld 3.0.0", "byte"),
        "episode_metadata/episode_seed": (episode.episode_seed, "int"),
        "episode_metadata/success": (int(episode.success), "int"),
        "steps/observation/state": (np.stack(episode.observations).reshape(-1), "float"),
        "steps/observation/image": ([image_jpeg_bytes(image) for image in episode.images], "byte"),
        "steps/action": (np.stack(episode.actions).reshape(-1), "float"),
        "steps/reward": (episode.rewards, "float"),
        "steps/discount": ([1.0] * (steps - 1) + [0.0], "float"),
        "steps/is_first": (is_first, "int"),
        "steps/is_last": (is_last, "int"),
        "steps/is_terminal": (is_last, "int"),
        "steps/timestamp": ([index / fps for index in range(steps)], "float"),
        "steps/language_instruction": ([instruction] * steps, "byte"),
    })


def export_packages(
    out: Path,
    *,
    allocation: dict[str, int],
    collection_seed: int,
    max_steps: int,
    action_noise: float,
    image_size: int,
    fps: int,
) -> list[dict]:
    dataset = LeRobotDataset.create(
        REPO_ID,
        fps=fps,
        root=out,
        robot_type=ROBOT_TYPE,
        features=feature_contract(image_size),
        use_videos=True,
        image_writer_threads=8,
        image_writer_processes=0,
        data_files_size_in_mb=256,
        video_files_size_in_mb=512,
    )
    rlds_dir = out / "rlds" / "0.1.0"
    rlds_dir.mkdir(parents=True, exist_ok=True)
    rlds_path = rlds_dir / "qtail_metaworld-train.tfrecord-00000-of-00001"
    rlds_writer = TFRecordWriter(str(rlds_path))
    episode_rows: list[dict] = []
    episode_index = 0
    try:
        for task_index, task in enumerate(TASKS):
            required = allocation[task]
            env = create_env(task, collection_seed + task_index * 100_000)
            expert = ENV_POLICY_MAP[task]()
            accepted = 0
            attempt = 0
            try:
                while accepted < required and attempt < required * 10:
                    episode_seed = collection_seed + task_index * 100_000 + attempt
                    episode = collect_episode(
                        env,
                        expert,
                        task=task,
                        task_index=task_index,
                        episode_seed=episode_seed,
                        max_steps=max_steps,
                        action_noise=action_noise,
                        image_size=image_size,
                    )
                    attempt += 1
                    if not episode.success:
                        continue
                    for frame_index in range(len(episode.actions)):
                        last = frame_index == len(episode.actions) - 1
                        dataset.add_frame({
                            "observation.state": episode.observations[frame_index],
                            "observation.images.rgb": episode.images[frame_index],
                            "action": episode.actions[frame_index],
                            "reward": np.array([episode.rewards[frame_index]], dtype=np.float32),
                            "discount": np.array([0.0 if last else 1.0], dtype=np.float32),
                            "done": np.array([last], dtype=bool),
                            "success": np.array([episode.success and last], dtype=bool),
                            "task": task,
                        })
                    dataset.save_episode()
                    write_rlds_episode(rlds_writer, episode, fps)
                    episode_rows.append({
                        "episode_index": episode_index,
                        "task": task,
                        "task_group": "head" if task == "reach-v3" else "tail",
                        "episode_seed": episode_seed,
                        "steps": len(episode.actions),
                        "success": True,
                        "episode_return": episode.episode_return,
                    })
                    episode_index += 1
                    accepted += 1
            finally:
                env.close()
            if accepted != required:
                raise RuntimeError(f"Collected only {accepted}/{required} successful episodes for {task}")
    finally:
        rlds_writer.close()
    dataset.finalize()
    return episode_rows


def validate_rlds(out: Path, expected_rows: list[dict], image_size: int, fps: int) -> dict:
    rlds_path = out / "rlds" / "0.1.0" / "qtail_metaworld-train.tfrecord-00000-of-00001"
    required = {
        "steps/observation/state",
        "steps/observation/image",
        "steps/action",
        "steps/reward",
        "steps/discount",
        "steps/is_first",
        "steps/is_last",
        "steps/is_terminal",
        "steps/timestamp",
        "steps/language_instruction",
    }
    episode_count = 0
    frame_count = 0
    missing_field_count = 0
    nonfinite_value_count = 0
    corrupt_frame_count = 0
    terminal_failures = 0
    timestamp_failures = 0
    for record in tfrecord_loader(str(rlds_path), None):
        episode_count += 1
        missing_field_count += len(required.difference(record))
        steps = int(np.asarray(record.get("steps/is_first", [])).size)
        frame_count += steps
        if steps < 1:
            terminal_failures += 1
            continue
        state = np.asarray(record["steps/observation/state"], dtype=np.float32)
        actions = np.asarray(record["steps/action"], dtype=np.float32)
        rewards = np.asarray(record["steps/reward"], dtype=np.float32)
        timestamps = np.asarray(record["steps/timestamp"], dtype=np.float32)
        nonfinite_value_count += int((~np.isfinite(state)).sum())
        nonfinite_value_count += int((~np.isfinite(actions)).sum())
        nonfinite_value_count += int((~np.isfinite(rewards)).sum())
        if state.size != steps * 39 or actions.size != steps * 4 or rewards.size != steps:
            missing_field_count += 1
        if not (
            int(np.asarray(record["steps/is_first"])[0]) == 1
            and int(np.asarray(record["steps/is_last"])[-1]) == 1
            and int(np.asarray(record["steps/is_terminal"])[-1]) == 1
        ):
            terminal_failures += 1
        expected_timestamps = np.arange(steps, dtype=np.float32) / fps
        if timestamps.shape != expected_timestamps.shape or not np.allclose(timestamps, expected_timestamps, atol=1e-6):
            timestamp_failures += 1
        for encoded in np.asarray(record["steps/observation/image"]).reshape(-1):
            try:
                with Image.open(io.BytesIO(bytes(encoded))) as image:
                    image.load()
                    if image.convert("RGB").size != (image_size, image_size):
                        corrupt_frame_count += 1
            except Exception:
                corrupt_frame_count += 1
    expected_frames = sum(int(row["steps"]) for row in expected_rows)
    corrupt_rate = (corrupt_frame_count / frame_count) if frame_count else 1.0
    return {
        "loader": "tfrecord.reader.tfrecord_loader",
        "episode_count": episode_count,
        "expected_episode_count": len(expected_rows),
        "frame_count": frame_count,
        "expected_frame_count": expected_frames,
        "missing_required_field_count": missing_field_count,
        "nonfinite_value_count": nonfinite_value_count,
        "terminal_semantics_failures": terminal_failures,
        "timestamp_failures": timestamp_failures,
        "corrupt_frame_count": corrupt_frame_count,
        "corrupt_frame_rate": corrupt_rate,
        "passed": all((
            episode_count == len(expected_rows),
            frame_count == expected_frames,
            missing_field_count == 0,
            nonfinite_value_count == 0,
            terminal_failures == 0,
            timestamp_failures == 0,
            corrupt_rate < 0.001,
        )),
    }


def validate_lerobot(out: Path, expected_rows: list[dict], image_size: int, fps: int) -> dict:
    metadata = LeRobotDatasetMetadata(REPO_ID, root=out)
    dataset = LeRobotDataset(REPO_ID, root=out, return_uint8=True)
    expected_frames = sum(int(row["steps"]) for row in expected_rows)
    sample_indices = sorted({0, len(dataset) // 2, len(dataset) - 1})
    sample_shapes: list[dict] = []
    for sample_index in sample_indices:
        sample = dataset[sample_index]
        state = sample["observation.state"]
        action = sample["action"]
        image = sample["observation.images.rgb"]
        if state.shape != torch.Size([39]) or action.shape != torch.Size([4]) or image.shape != torch.Size([3, image_size, image_size]):
            raise RuntimeError(f"Official LeRobot loader returned invalid shapes at {sample_index}")
        if not torch.isfinite(state).all() or not torch.isfinite(action).all():
            raise RuntimeError(f"Official LeRobot loader returned non-finite tensors at {sample_index}")
        sample_shapes.append({
            "index": sample_index,
            "state": list(state.shape),
            "action": list(action.shape),
            "image": list(image.shape),
        })
    batch = next(iter(DataLoader(dataset, batch_size=4, shuffle=False, num_workers=0)))
    first_image = dataset[0]["observation.images.rgb"].permute(1, 2, 0).cpu().numpy()
    Image.fromarray(first_image.astype(np.uint8), mode="RGB").save(out / "sample_playback.png")
    passed = all((
        int(metadata.total_episodes) == len(expected_rows),
        int(metadata.total_frames) == expected_frames,
        int(metadata.fps) == fps,
        metadata.robot_type == ROBOT_TYPE,
        tuple(batch["action"].shape) == (4, 4),
    ))
    return {
        "loader": "lerobot.datasets.LeRobotDataset 0.6.0",
        "official_metadata_load": True,
        "episode_count": int(metadata.total_episodes),
        "expected_episode_count": len(expected_rows),
        "frame_count": int(metadata.total_frames),
        "expected_frame_count": expected_frames,
        "fps": int(metadata.fps),
        "robot_type": metadata.robot_type,
        "camera_keys": list(metadata.camera_keys),
        "sample_shapes": sample_shapes,
        "dataloader_batch_action_shape": list(batch["action"].shape),
        "passed": passed,
    }


def write_json(path: Path, value: dict | list) -> None:
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_metadata(out: Path, allocation: dict[str, int], episode_rows: list[dict], fps: int, image_size: int) -> None:
    rlds_dir = out / "rlds" / "0.1.0"
    write_json(rlds_dir / "dataset_info.json", {
        "name": "qtail_metaworld_sawyer",
        "version": "0.1.0",
        "description": "Q-Tail allocated synthetic Sawyer trajectories executed in MetaWorld/MuJoCo.",
        "format": "RLDS-compatible flattened episode TFRecord",
        "episode_count": len(episode_rows),
        "frame_count": sum(int(row["steps"]) for row in episode_rows),
        "fps": fps,
        "robot_type": ROBOT_TYPE,
        "production_backend": "MuJoCo 3.10.0 / MetaWorld 3.0.0 MT1",
        "tasks": list(TASKS),
        "allocation": allocation,
        "license": "MetaWorld MIT; generated trajectories released for Q-Tail evaluation subject to package terms.",
    })
    write_json(rlds_dir / "features.json", {
        "observation.state": {"dtype": "float32", "shape": [39]},
        "observation.image": {"dtype": "jpeg", "shape": [image_size, image_size, 3]},
        "action": {"dtype": "float32", "shape": [4]},
        "reward": {"dtype": "float32", "shape": []},
        "discount": {"dtype": "float32", "shape": []},
        "is_first": {"dtype": "bool", "shape": []},
        "is_last": {"dtype": "bool", "shape": []},
        "is_terminal": {"dtype": "bool", "shape": []},
        "timestamp": {"dtype": "float32", "shape": []},
        "language_instruction": {"dtype": "string", "shape": []},
    })
    write_json(out / "robot_contract.json", {
        "robot_model": "Sawyer 7-DoF arm (MetaWorld abstraction)",
        "action_contract": "4D normalized Cartesian delta plus gripper command, clipped to [-1, 1]",
        "state_contract": "39D MetaWorld MT1 observation",
        "sensor_contract": f"{image_size}x{image_size} RGB simulator camera plus 39D state",
        "control_frequency_hz": fps,
        "renderer": "MuJoCo rgb_array",
        "training_formats": ["LeRobotDataset v3", "RLDS-compatible TFRecord"],
        "physical_validity_boundary": "Simulator embodiment only; no camera calibration or real Sawyer execution is claimed.",
    })
    (out / "METAWORLD_LICENSE.txt").write_text((ROOT.parent / "Metaworld" / "LICENSE").read_text(encoding="utf-8"), encoding="utf-8")


def build_manifest(out: Path, allocation: dict[str, int], validations: dict) -> tuple[Path, str]:
    artifact_files = sorted(
        path for path in out.rglob("*")
        if path.is_file() and path.name not in {"package_manifest.json", "gate1_acceptance_report.json"}
    )
    entries = [
        {"path": str(path.relative_to(out)), "bytes": path.stat().st_size, "sha256": sha256_file(path)}
        for path in artifact_files
    ]
    manifest = {
        "product": "qtail_gate1_metaworld_synthetic_trajectory_package",
        "generated_at": now(),
        "formats": ["LeRobotDataset v3.0", "RLDS-compatible TFRecord"],
        "robot_type": ROBOT_TYPE,
        "production_backend": "MuJoCo 3.10.0 / MetaWorld 3.0.0 MT1",
        "selection_method": "Q-Tail tail-rebalanced allocation used by the controlled Gate 2 study",
        "trajectory_allocation": allocation,
        "trajectory_count": sum(allocation.values()),
        "frame_count": validations["lerobot"]["frame_count"],
        "files": entries,
        "total_bytes": sum(item["bytes"] for item in entries),
        "claim_boundary": [
            "These are newly executed synthetic MetaWorld/MuJoCo trajectories, not public Open X re-exports.",
            "The package proves a narrow local simulator production path and trainable format validation only.",
            "It is not buyer-specific production-backend evidence, a real-robot run, an invoice, or procurement acceptance.",
        ],
    }
    manifest_path = out / "package_manifest.json"
    write_json(manifest_path, manifest)
    return manifest_path, sha256_file(manifest_path)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate and validate a synthetic MetaWorld Sawyer Gate 1 package.")
    parser.add_argument("--allocation", type=parse_allocation, default=DEFAULT_ALLOCATION)
    parser.add_argument("--collection-seed", type=int, default=20260715)
    parser.add_argument("--max-steps", type=int, default=200)
    parser.add_argument("--expert-action-noise", type=float, default=0.02)
    parser.add_argument("--image-size", type=int, default=256)
    parser.add_argument("--fps", type=int, default=20)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--require-pass", action="store_true")
    args = parser.parse_args()
    if args.max_steps < 1 or args.image_size < 64 or args.fps < 1:
        raise SystemExit("max steps, image size, and fps must be positive; image size must be at least 64")
    out = args.out.resolve()
    if out.exists():
        if not args.overwrite:
            raise SystemExit(f"Output exists: {out}; pass --overwrite to replace it")
        shutil.rmtree(out)

    episode_rows = export_packages(
        out,
        allocation=args.allocation,
        collection_seed=args.collection_seed,
        max_steps=args.max_steps,
        action_noise=args.expert_action_noise,
        image_size=args.image_size,
        fps=args.fps,
    )
    write_metadata(out, args.allocation, episode_rows, args.fps, args.image_size)
    write_json(out / "trajectory_index.json", episode_rows)
    validations = {
        "lerobot": validate_lerobot(out, episode_rows, args.image_size, args.fps),
        "rlds": validate_rlds(out, episode_rows, args.image_size, args.fps),
    }
    validation_passed = all(item["passed"] for item in validations.values())
    manifest_path, manifest_sha256 = build_manifest(out, args.allocation, validations)
    report = {
        "gate": 1,
        "status": "passed_simulator_production_baseline" if validation_passed else "validation_failed",
        "generated_at": now(),
        "trajectory_count": len(episode_rows),
        "frame_count": sum(int(row["steps"]) for row in episode_rows),
        "robot_type": ROBOT_TYPE,
        "production_backend": "MuJoCo 3.10.0 / MetaWorld 3.0.0 MT1",
        "trajectory_allocation": args.allocation,
        "validation": validations,
        "package_manifest": str(manifest_path),
        "package_manifest_sha256": manifest_sha256,
        "evidence_level": "local synthetic simulator production baseline",
        "buyer_gate_passed": False,
        "buyer_gate_status": "requires buyer-selected robot/backend execution and signed buyer acceptance",
    }
    write_json(out / "gate1_acceptance_report.json", report)
    print(json.dumps(report, ensure_ascii=False, indent=2))
    if args.require_pass and not validation_passed:
        raise SystemExit(2)


if __name__ == "__main__":
    main()
